name: unit_converter
description: A Flutter app for converting different units.
publish_to: 'none' # Remove this line if you intend to publish to the store

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1  # Use the latest version or the version that works for your project.
  material_color_utilities: ^0.11.1  # Updated version


dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.2  # Updated version of fake_async
  leak_tracker: ^10.0.8  # Updated version of leak_tracker
  vm_service: ^14.3.1  # Updated version of vm_service

flutter:
  uses-material-design: true
